### ISSUE TITLE
Launch revamped vue3 site

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/printnanny-os#50]
**Describe your Request**
Blocks work on PrintNanny's desktop app. Most UI work in general is blocked right now, due to the amount of technical debt in front-end code. There's a mix of 2 build systems (Webpack / Gulp) and 2 template systems (Vue / Django SSR via Jinja), and a very old version of Vue. This makes any UI work super painful and unpleasant. 

I put together a quick rewrite, implemented in Vue3. I'm committing fully to SPA design, which will force me to exercise/build the UI code regularly. This will also make it easier to release the UI as a desktop app later this summer. 

Django will continue to serve all /api endpoints defined in OpenAPI schema. 

## Todo

- [x] Landing view
- [x] Signup
- [x] Login/logout
- [x] Dashboard with sidebar nav and main content area
- [x] Device connections list/create
- [x] Sticky alerts component
- [x] Sticky footer with link tree
- [x] Privacy Policy view
- [x] Terms of Service view
- [x] Billing view
- [x] Settings view
- [x] Ensure UI is served via CDN

**Screenshots or Mockups**
Work-in-progress. I started a few days ago, after I gave up trying to fix broken dependencies in the old UI build. 
![Screenshot from 2022-07-15 16-27-38](https://user-images.githubusercontent.com/2601819/179324738-62426398-8220-4635-84c5-3e81d74d8982.png)
